### ISSUE TITLE
updating installed simpleITK with current master branch

### ISSUE THREAD

**Issue by bishesh** [SimpleITK/SimpleITKCondaRecipe#18]
I have just installed simpleitk-1.0.0-py36_0 with this recipe.

```
git clone https://github.com/SimpleITK/SimpleITKCondaRecipe.git

cd SimpleITKCondaRecipe

conda build recipe

conda install --use-local simpleitk

``` 

I want to now keep this installation up to date with the current master branch of simpleitk.
How can I do that ? 
Is there a way to do this without rebuilding the whole of ITK again ?
If not, how to cleanly uninstall the version I have just installed to restart again ?

**Comment by zivy** [comment]
If you used the recipe as is without modification then you will always get SimpleITK version 1.0.0 as this is what is specified in the meta.yaml file.

If you want to use the master branch then you will need to edit this file as described in the [instructions](https://github.com/SimpleITK/SimpleITKCondaRecipe#process).

With regard to rebuilding, for simplicity's sake, I would recommend building from scratch every time (lets say, every other month). 

To uninstall a package from a virtual environment, or root environment, you first activate the environment and then "conda remove simpleitk" 

Also I get the impression you installed SimpleITK into the root anaconda environment and that you are not using virtual environments. This is not recommended as you will not have a stable development environment.  This is general practice for Anaconda and is not specific to usage of SimpleITK.

Anaconda enables you to maintain a stable development environment using virtual environments.
A recommended workflow would be:
1. Create a virtual environment called sitkpy with python 3.6: "conda create -n sitkpy python=3.6 anaconda"
2.  Activate it: "source activate sitkpy"
3. Build simpleitk from recipe.
4. Install simpleitk (will be into your current environment which is sitkpy): "conda install --use-local simpleitk"
5. Work on your project.
6. Later on, you want to update simpleitk (it is possible that changes in simpleitk/any updated package will break your project).
7. Create a [copy of the sitkpy virtual environment](https://conda.io/docs/using/envs.html#clone-an-environment), you will test your work against the new simpleitk version here.
8. Activate the new environment.
9. Uninstall simpleitk from this test environment and install the new version. Test your code. If everything is working then you can install the new simpleitk in your development environment and continue working. If not: (1) you have uncovered a bug - report it on the SimpleITK github issue tracker, (2) the simpleITK API has changed - you will need to modify your code or keep the old version of simpleitk.
