### ISSUE TITLE
Can I build the latest version in Windows 10?

### ISSUE THREAD

**Issue by sdalxn** [SimpleITK/SimpleITKCondaRecipe#25]
Can I build the latest version in Windows 10?
When I run the statement "conda build recipe", the program is stay at some point. It looks like below in cmd window. 

`C:\SimpleITKCondaRecipe>conda build recipe
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for simpleitk
INFO:conda_build.metadata:Attempting to finalize metadata for simpleitk
BUILD START: [u'simpleitk-1.1.1-py27_0.tar.bz2']

The following NEW packages will be INSTALLED:

    certifi:        2018.1.18-py27_0 conda-forge
    cmake:          3.10.0-4         conda-forge
    jpeg:           9b-vc9_2         conda-forge [vc9]
    libpng:         1.6.34-vc9_0     conda-forge [vc9]
    libtiff:        4.0.9-vc9_0      conda-forge [vc9]
    pip:            9.0.1-py27_1     conda-forge
    python:         2.7.14-4         conda-forge
    setuptools:     38.5.2-py27_0    conda-forge
    swig:           3.0.12-2         conda-forge
    vc:             9-0              conda-forge
    vs2008_runtime: 9.0.30729.6161-0 conda-forge
    vs2015_runtime: 14.0.25420-0     conda-forge
    wheel:          0.30.0-py27_2    conda-forge
    wincertstore:   0.2-py27_0       conda-forge
    zlib:           1.2.11-vc9_0     conda-forge [vc9]`

Could I do something? Any suggestion will be appreciated.

**Comment by blowekamp** [comment]
I am working are creating some 1.1rc2 packaging for the anaconda cloud now. These are based on the official anaconda distributions, and not conda-forge. The builds and packaging are going OK. We have run into problems with the VS9 linker from time to time but recent efforts to reduce the number of symbols in SimpleITK seem to have been effective and we should have both win32 and win64 binaries for Python 2.7.

The build processes for SimpleITK is quite length. You are not including the the error message from the build process so I am not sure what is happening on your system. Do you have Visual Studio 9 installed or VS for Python?

**Comment by sdalxn** [comment]
@blowekamp You are right. The build process is very long and at last I got the error information. Because I have not installed VS 9  although I had installed VS14.
I have got the 1.1rc2 version from the website https://discourse.itk.org/t/simpleitk-1-1-release-candidate-1/664.
Thank you for your help.

**Comment by blowekamp** [comment]
Thanks for letting us know how you resolved the problem.
