### ISSUE TITLE
Could GetMetaDataKeys function get all the metadata key?

### ISSUE THREAD

**Issue by sdalxn** [SimpleITK/SimpleITKCondaRecipe#26]
I have installed SimpleITK 1.1 rc1. But I found it seems that the function GetMetaDataKeys of ImageSeriesReader could not get all the metadata keys.

``def get_img_from_dcm_files(dest_directory, dcm_directory, ext):
    '''
    get iamge files whose format are specified by extension from dicom series files
    :param dest_directory:target files directory string
    :param dcm_directory:dicom files directory string
    :param ext:files extension string
    :return:None
    '''
    series_reader = sitk.ImageSeriesReader()
    series_IDs = series_reader.GetGDCMSeriesIDs(dcm_directory)

    if not series_IDs:
        print("ERROR: given directory \"" + dcm_directory + "\" does not contain a DICOM series.")
        sys.exit(1)

    series_file_names = series_reader.GetGDCMSeriesFileNames(dcm_directory, series_IDs[0])
    series_reader.SetFileNames(series_file_names)

    series_reader.MetaDataDictionaryArrayUpdateOn()
    series_reader.LoadPrivateTagsOn()
    image3D = series_reader.Execute()

    for k in series_reader.GetMetaDataKeys(2):
        v = series_reader.GetMetaData(2,k)
        print("({0}) = = \"{1}\"".format(k, v))

The result is as follows:
`(0008|0005) = = "ISO_IR 100"
(0008|0008) = = "ORIGINAL\PRIMARY\M\ND\NORM"
(0008|0012) = = "20111110"
(0008|0013) = = "094123.531000 "
(0008|0016) = = "1.2.840.10008.5.1.4.1.1.4"
(0008|0018) = = "1.3.12.2.1107.5.2.30.25591.2011111009411414857727859"
(0008|0020) = = "20111110"
(0008|0021) = = "20111110"
(0008|0022) = = "20111110"
(0008|0023) = = "20111110"
(0008|0030) = = "093416.265000 "
(0008|0031) = = "094123.531000 "
(0008|0032) = = "093522.335000 "
(0008|0033) = = "094123.531000 "
(0008|0050) = = "19078400556130"
(0008|0060) = = "MR"
(0008|0070) = = "SIEMENS "
(0008|0080) = = "MRI Bahnhofplatz"
(0008|0081) = = "Bahnhofsplatz 3,Zuerich/5EB7E0/,Zuerich,CH,ZIP"
(0008|0090) = = ""
(0008|1010) = = "HB-MRC"
(0008|1030) = = "Sch�del - Neuro^Orbita"
(0008|103e) = = "t2_spc_flair_irprep_sag_p2_iso"
(0008|1040) = = "MR3_HB"
(0008|1048) = = "StTo"
(0008|1050) = = "StTo"
(0008|1090) = = "Avanto"
(0010|0010) = = "Adamos^Kyriacon "
(0010|0020) = = "556130"
(0010|0021) = = "PrimaryDomain "
(0010|0030) = = "19870113"
(0010|0032) = = "000000.000000 "
(0010|0040) = = "M "
(0010|1010) = = "024Y"
(0010|1030) = = "88"
(0010|1040) = = "Spitalgasse 9^^Z�rich^CH^8001^"
(0018|0020) = = "SE\IR "
(0018|0021) = = "SK\SP\MP"
(0018|0022) = = "IR\PFP"
(0018|0023) = = "3D"
(0018|0024) = = "*spcir3d1_274ns "
(0018|0025) = = "N "
(0018|0050) = = "1 "
(0018|0080) = = "5000"
(0018|0081) = = "335 "
(0018|0082) = = "1800"
(0018|0083) = = "1 "
(0018|0084) = = "63.667864 "
(0018|0085) = = "1H"
(0018|0086) = = "1 "
(0018|0087) = = "1.5 "
(0018|0089) = = "204 "
(0018|0091) = = "137 "
(0018|0093) = = "97.6563 "
(0018|0094) = = "100 "
(0018|0095) = = "592 "
(0018|1000) = = "25591 "
(0018|1020) = = "syngo MR B17"
(0018|1030) = = "t2_spc_flair_irprep_sag_p2_iso"
(0018|1251) = = "Body"
(0018|1310) = = "0\256\250\0"
(0018|1312) = = "ROW "
(0018|1314) = = "120 "
(0018|1315) = = "Y "
(0018|1316) = = "0.0581332283704 "
(0018|1318) = = "0 "
(0018|5100) = = "HFS "
(0019|0010) = = "SIEMENS MR HEADER "
(0019|1008) = = "IMAGE NUM 4 "
(0019|1009) = = "1.0 "
(0019|100b) = = "347220"
(0019|100f) = = "Fast"
(0019|1011) = = "No"
(0019|1012) = = "0\0\-994"
(0019|1013) = = "0\0\-994"
(0019|1014) = = "0\0\0 "
(0019|1015) = = "-87.5\-139.843\116.904"
(0019|1017) = = "0.795455"
(0019|1018) = = "3300"
(0020|000d) = = "1.2.124.113532.30.20265.59073.20111107.74456.11664418"
(0020|000e) = = "1.3.12.2.1107.5.2.30.25591.2011111009411419957127863.0.0.0"
(0020|0010) = = "19078400556130"
(0020|0011) = = "2 "
(0020|0012) = = "1 "
(0020|0013) = = "1 "
(0020|0032) = = "-87.5\-139.84337329865\116.90361404419"
(0020|0037) = = "0\1\0\0\0\-1"
(0020|0052) = = "1.3.12.2.1107.5.2.30.25591.1.20111110093416406.0.0.0"
(0020|1040) = = ""
(0020|1041) = = "-87.5 "
(0028|0002) = = "1"
(0028|0004) = = "MONOCHROME2 "
(0028|0010) = = "256"
(0028|0011) = = "256"
(0028|0030) = = "0.9765625\0.9765625 "
(0028|0100) = = "16"
(0028|0101) = = "12"
(0028|0102) = = "11"
(0028|0103) = = "0"
(0028|0106) = = "0"
(0028|0107) = = "21"
(0028|1050) = = "10"
(0028|1051) = = "21"
(0028|1055) = = "Algo1 "
(0029|0010) = = "SIEMENS CSA HEADER"
(0029|0011) = = "SIEMENS MEDCOM HEADER2"
(0029|1008) = = "IMAGE NUM 4 "
(0029|1009) = = "20111110"
(0029|1010) = = "********="
(0029|1018) = = "MR"
(0029|1019) = = "20111110"
(0029|1020) = = "U1YxMAQDAgFBAAAATQAAAFVzZWRQYXRpZW50V2VpZ2h0ACluAAAAAAAAAACISnpOAAAAAAAAAAAgPFBhqKrKCaiqygk4q8oJAFVDb3VudCIBAAAASVMAAAYAAAAGAAAATQAAAAkAAAAJAAAATQAAAAkA**AAAAAAAAAAAA="
(0029|1160) = = "com "
(0032|000a) = = "SCHEDULED "
(0032|1032) = = "StTo"
(0032|1033) = = "UNKNOWN "
(0032|1060) = = "MRI Orbita"
(0040|0244) = = "20111110"
(0040|0245) = = "093416.343000 "
(0040|0253) = = "19078400556130"
(0040|0254) = = "MRI Orbita"
(0051|0010) = = "SIEMENS MR HEADER "
(0051|1008) = = "IMAGE NUM 4 "
(0051|1009) = = "1.0 "
(0051|100a) = = "TA 05:47"
(0051|100b) = = "250p*256"
(0051|100c) = = "FoV 250*250 "
(0051|100d) = = "SP R87.5"
(0051|100e) = = "Sag "
(0051|100f) = = "C:HEA;HEP "
(0051|1011) = = "p2"
(0051|1012) = = "TP 0"
(0051|1013) = = "+LPH"
(0051|1015) = = "R "
(0051|1016) = = "p2 M/ND/NORM"
(0051|1017) = = "SL 1.0i "
(0051|1019) = = "A1/IR/PFP "`

I implement this function. But I found it could not print the info about the group “0002”,such as 0002 0000; 0002 0001; 0002 0002...

And It could not get the information about the group 0008 1110 and  0008 1140 .They are two SQ data elements.

And It could not got the information about nested group.

Although I do not need these information now, I think it is better if I can get it intact.

Or doI use it wrong?

**Comment by blowekamp** [comment]
This issue should be raise in the SimpleITK/SimpleITK project.
