### ISSUE TITLE
Simple Elastix

### ISSUE THREAD

**Issue by ryancinsight** [SimpleITK/SimpleITKCondaRecipe#39]
Would it be possible to modify this to also install the simple elastix in the superbuild or is it already doing that?

**Comment by blowekamp** [comment]
SimpleElastix is forked from SimpleITK, developed and maintained by the Elastix team. It should be relatively easy adapt this CondaRecipe to build the [SimpleElastix repo](https://github.com/SuperElastix/SimpleElastix).

**Comment by blowekamp** [comment]
Closing as it asks about a separate project.
