### ISSUE TITLE
finding wrong SWIG on path

### ISSUE THREAD

**Issue by grlee77** [SimpleITK/SimpleITKCondaRecipe#4]
Thanks for making this recipe available.

I tried running it today (via `conda build -c conda-forge recipe`) and had problems with it finding the system SWIG in `/usr/bin/swig2.0` (on Ubuntu 12.04) rather than the SWIG 3.0.2 that was in `~/anaconda/bin/swig`.  Adding the following CMAKE option to `build.sh` fixed this:

```
-D "SWIG_EXECUTABLE:FILEPATH=${PREFIX}/bin/swig" \
```

To be consistent with the current `conda-forge` version pinnings (see: https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/pin_the_slow_way.py), I also updated some versions in `meta.yaml` to:

```
    - libpng   >=1.6.28,<1.7
    - jpeg     9*
    - zlib     1.2.*
```

I verified that the build completed successfully on both linux and OS X.

**Comment by blowekamp** [comment]
Good catch! Care to make a pull request with your fix?

**Comment by grlee77** [comment]
sure.  see #4

**Comment by blowekamp** [comment]
Is there a way that we can work on the standard conda installed versions, yet still be compatible with the latest versions on condo forge?

**Comment by grlee77** [comment]
I am not sure.  As commented in #9, it will eventually best to have a feedstock over at `conda-forge` that can stay synced with the `conda-forge` pinnings.  I see you have already made such a PR at conda-forge/staged-recipes#1045.  There has been some discussion of a way to either extend or get around the time limits on the CI services, but no concrete resolution to that so far as I am aware.

**Comment by blowekamp** [comment]
The recipe has been updated and the SWIG path work across platforms.
