### ISSUE TITLE
Multiple definition error during linking of SimpleITK build with Elastix

### ISSUE THREAD

**Issue by kaftanski** [SimpleITK/SimpleITKCondaRecipe#85]
I am trying to build SimpleITK 2.2.1 with SimpleElastix enabled on an aarch64 server (Neoverse N1) but during linking of the SimpleITK wrapping, I get the following linking error:
```
[987/987] Linking CXX shared module Wrapping/Python/SimpleITK/_SimpleITK.so
FAILED: Wrapping/Python/SimpleITK/_SimpleITK.so 
$BUILD_PREFIX/bin/../lib/gcc/aarch64-conda-linux-gnu/11.2.0/../../../../aarch64-conda-linux-gnu/bin/ld.gold: error: $SRC_DIR/build/ITK-prefix/lib/libITKCommon-5.3.a(itkNumericTraits.cxx.o): multiple definition of 'itk::NumericTraits<unsigned char>::Zero'
$BUILD_PREFIX/bin/../lib/gcc/aarch64-conda-linux-gnu/11.2.0/../../../../aarch64-conda-linux-gnu/bin/ld.gold: lib/libSimpleITK_ITKSuperPixel-2.2.a(sitkSLICImageFilter.cxx.o): previous definition here
```
I used the `conda build recipe` method and made only the change of adding `-D SimpleITK_USE_ELASTIX:BOOL=ON` to the cmake arguments in `build.sh`. Full build log: [build_log.txt](https://github.com/SimpleITK/SimpleITKCondaRecipe/files/12192436/build_log.txt)

A similar error was reported in https://github.com/SimpleITK/SimpleITK/issues/1732 but not reproducible. Did you get any more insight into why this happened @kaspermarstal?

Versions of relevant tools are:
- OS: Ubuntu 22.04.1 LTS (aarch64)
- Python 3.9.17
- gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
- cmake 3.26.4

Please let me know if you need any more information and thank you for your help!

**Comment by blowekamp** [comment]
I would suggest trying the "[v2.3rc1](https://github.com/SimpleITK/SimpleITK/releases/tag/v2.3rc1)" as the issues may have been addressed.

Also we are considering stopping support for this conda package with dependencies on conda libs, and only supporting the conda-forge, and pypi packages. Building a wheel directly from the SimpleITK repository may be easier than in cond, and certainly easier to update configurations with out rebuilding.

**Comment by kaftanski** [comment]
Thank you very much, setting this version resolved the errors! Also thanks for pointing this out. For future projects I will look into these other builds.
