### ISSUE TITLE
Simple ITK

### ISSUE THREAD

**Issue by mohi-gs** [SimpleITK/SimpleITKCondaRecipe#87]
Hi Im using Spyder and anacnda and i have codes of simpleITK in it but it has error in readimage and i cant solve it my files are ok i do resized and change them to nifti too do you have any opinion why this happen?

**Comment by zivy** [comment]
Hello @mohi-gs,

Please share a minimal working code example illustrating the error. Also, you need to specify the error message so that we can help you resolve it. It could be as simple as the path you are providing to `sitk.ReadImage()` being incorrect (relative path and the working directory of Spyder's Python shell is not what you think it is).

**Comment by mohi-gs** [comment]
Hello 
I want to do n4biasfield correction on nifti images with simpleitk and the code have to read those images to do process on them .the error said its unable to open the files path or there is no attribute for Readimage code in simpleitk

**Comment by zivy** [comment]
Hello @mohi-gs,

The example script for bias field correction is available from [read the docs](https://simpleitk.readthedocs.io/en/master/link_N4BiasFieldCorrection_docs.html). It is widely used, so should work for you. 

Also, when reporting an error, please **copy paste** the error. Your description lists two errors "file path" issue and "no attribute" issue these cannot happen at the same time.

I would recommend that you create a clean virtual environment, install SimpleITK there and then try it. The following creates a new anaconda environment called `sitk` with Python 3.11 and SimpleITK:
```
conda create --name sitk python=3.11 simpleitk --channel conda-forge --override-channels
```

**Comment by mohi-gs** [comment]
Hello @zivy 
thank you for your help now i can read the files but i cant write them!

**Comment by zivy** [comment]
Hello @mohi-gs,

Were you able to run the script from the SimpleITK read the docs examples in the new conda environment? If yes, it also writes the output to file. If not, please copy the error message and paste it here. 

Also, if you want us to be able to help you, you need to provide relevant information in your posts, "cant write them" is very generic and we don't have any idea why this could be. Is your computer out of disk space? Do you have write permission to the location where you want to write? These are just two issues that can cause writing to fail and have nothing to do with SimpleITK. The more details you provide about the problem the easier it is for others to help you debug.

**Comment by mohi-gs** [comment]
hello @zivy 
very thank you for your help The problem is on the file path and after I changed it ,it solved. thank you very much
